from __future__ import annotations

PREDICTION_METRICS = [
    {
        "name": "Next-event accuracy",
        "category": "Level 1: Prediction evaluation",
        "metric_type": "Classification",
        "short_purpose": "Measures how often the model predicts the correct next rhythmic-event token on held-out recordings.",
        "formula": "Accuracy = correct next-event predictions / total next-event predictions",
        "direction": "Higher is better",
        "interpretation": "Higher values mean the model selected the actual next event more often.",
        "implementation": "src.metrics.evaluation.accuracy_score(y_true, y_pred)",
    },
    {
        "name": "Top-k accuracy",
        "category": "Level 1: Prediction evaluation",
        "metric_type": "Ranked prediction",
        "short_purpose": "Checks whether the correct next token appears within the model's top-k predicted choices.",
        "formula": "Top-k accuracy = cases where true token is in top-k predictions / total cases",
        "direction": "Higher is better",
        "interpretation": "Higher values mean the model often placed the correct event among its most likely options.",
        "implementation": "custom top-k check from predicted probability table",
    },
    {
        "name": "Macro F1-score",
        "category": "Level 1: Prediction evaluation",
        "metric_type": "Class-balanced",
        "short_purpose": "Gives each event class equal weight so frequent tokens do not dominate the score.",
        "formula": "Macro F1 = mean(F1 score across event classes)",
        "direction": "Higher is better",
        "interpretation": "Higher values mean prediction is more balanced across frequent and less frequent event tokens.",
        "implementation": "src.metrics.evaluation.macro_f1_score(y_true, y_pred, labels=vocabulary_ids)",
    },
    {
        "name": "Probabilistic loss",
        "category": "Level 1: Prediction evaluation",
        "metric_type": "Probability quality",
        "short_purpose": "Measures how well the model assigns probability to the actual next event, not only whether the top choice is correct.",
        "formula": "Loss = - mean(log probability assigned to the true next token)",
        "direction": "Lower is better",
        "interpretation": "Lower loss means the model gave stronger probability support to the actual next events.",
        "implementation": "cross-entropy for GRU/LSTM; negative log-likelihood or equivalent for Markov Chain/N-gram",
    },
]

GENERATION_METRICS = [
    {
        "name": "Transition validity / sequence coherence",
        "category": "Level 1: Generation evaluation",
        "metric_type": "Generated sequence structure",
        "short_purpose": "Checks whether generated event transitions are valid or observed under the reference representation.",
        "formula": "Transition validity = valid generated transitions / total generated transitions",
        "direction": "Higher is better",
        "interpretation": "Higher values mean the generated sequence follows more plausible event-to-event movement.",
        "implementation": "custom transition lookup from reference or training transition table",
    },
    {
        "name": "Distribution similarity",
        "category": "Level 1: Generation evaluation",
        "metric_type": "Reference similarity",
        "short_purpose": "Compares generated token or IOI distributions with the reference data.",
        "formula": "Jensen-Shannon distance or comparable bounded distance between generated and reference distributions",
        "direction": "Lower distance is generally better",
        "interpretation": "Lower distance means generated distributions are closer to the reference distributions.",
        "implementation": "scipy.spatial.distance.jensenshannon or custom normalized distribution distance",
    },
    {
        "name": "Strike-density difference",
        "category": "Level 1: Generation evaluation",
        "metric_type": "Rhythmic density",
        "short_purpose": "Checks whether generated sequences are too sparse or too crowded compared with reference recordings.",
        "formula": "Density difference = abs(generated strikes per second - reference strikes per second)",
        "direction": "Lower is generally better",
        "interpretation": "Lower difference means the generated rhythm is closer to the reference density.",
        "implementation": "custom density calculation from event count and duration or IOI-derived timing",
    },
    {
        "name": "Short-pattern preservation",
        "category": "Level 1: Generation evaluation",
        "metric_type": "Local pattern structure",
        "short_purpose": "Checks whether two-token or three-token rhythmic patterns from the reference data appear in generated sequences.",
        "formula": "Pattern preservation = generated reference-matching n-grams / total generated n-grams",
        "direction": "Balanced higher values are preferred",
        "interpretation": "Higher values suggest local rhythmic-event patterns are preserved without proving cultural authenticity.",
        "implementation": "custom bigram/trigram overlap against reference n-gram set",
    },
    {
        "name": "Repetition behavior",
        "category": "Level 1: Generation evaluation",
        "metric_type": "Memorization / collapse check",
        "short_purpose": "Detects excessive repeated tokens, repeated patterns, and exact training-pattern overlap.",
        "formula": "Repetition rate = repeated units / total comparable units",
        "direction": "Interpret with context",
        "interpretation": "Some repetition is expected in rhythm, but excessive repetition can indicate memorization or generation collapse.",
        "implementation": "custom repeated-token, repeated-n-gram, and training-copy checks",
    },
    {
        "name": "Generation validity and diversity",
        "category": "Level 1: Generation evaluation",
        "metric_type": "Validity / diversity",
        "short_purpose": "Checks whether generated outputs are valid event sequences and whether repeated samples are not all identical.",
        "formula": "Validity = valid tokens / total tokens; Diversity = unique sequences or unique n-grams / total",
        "direction": "Valid outputs should be high; diversity should be balanced",
        "interpretation": "High validity is required; low diversity suggests collapse while unstable high diversity may suggest randomness.",
        "implementation": "custom valid-token, unique-sequence, and distinct-n calculations",
    },
    {
        "name": "Rendering readiness",
        "category": "Level 1: Audio-output check",
        "metric_type": "Technical output validation",
        "short_purpose": "Checks whether each generated token's strength category can select an accepted performance-derived sample for a future WAV simulation.",
        "formula": "Renderable rate = renderable generated tokens / total generated tokens",
        "direction": "Higher is better",
        "interpretation": "This validates token-to-sample rendering, not musical beauty or cultural authenticity.",
        "implementation": "planned strength-category sample-bank coverage and mapping validation",
    },
]

EFFICIENCY_METRICS = [
    {
        "name": "Training time and epochs",
        "category": "Level 1: Efficiency evaluation",
        "metric_type": "Runtime / convergence",
        "short_purpose": "Measures how long each algorithm takes and how many epochs are needed for neural models.",
        "formula": "Training time = end time - start time",
        "direction": "Lower is generally better if performance remains acceptable",
        "interpretation": "Useful for judging practical suitability under a low-resource local research setup.",
        "implementation": "custom runtime logs and training-history records",
        "availability": "current",
    },
    {
        "name": "Model size / memory requirement",
        "category": "Level 1: Efficiency evaluation",
        "metric_type": "Resource use",
        "short_purpose": "Compares how heavy each model is to store and run.",
        "formula": "Model size = saved artifact size or parameter count",
        "direction": "Lower is generally more efficient",
        "interpretation": "Helps compare the simple baseline with recurrent neural models under local-resource constraints.",
        "implementation": "artifact size, parameter count, or memory-use record",
        "availability": "planned",
    },
    {
        "name": "Training-to-held-out gap",
        "category": "Level 1: Overfitting evidence",
        "metric_type": "Generalization check",
        "short_purpose": "Compares training/validation performance with held-out recording performance.",
        "formula": "Gap = training metric - held-out metric, adjusted by metric direction",
        "direction": "Smaller harmful gap is preferred",
        "interpretation": "Large gaps may indicate memorization, especially for GRU and LSTM in low-resource data.",
        "implementation": "custom comparison of training, validation, and held-out logs",
        "availability": "planned",
    },
    {
        "name": "Seed variability",
        "category": "Level 1: Stability evaluation",
        "metric_type": "Run stability",
        "short_purpose": "Checks whether neural results change substantially across repeated random seeds.",
        "formula": "Seed variability = standard deviation of metric across repeated seed runs",
        "direction": "Lower harmful variability is preferred",
        "interpretation": "High variability means results may depend strongly on initialization or sampling conditions.",
        "implementation": "repeat selected neural runs with recorded seed values",
        "availability": "planned",
    },
]

STATISTICAL_TREATMENTS = [
    {
        "name": "Fold-level comparison",
        "category": "Level 2: Statistical treatment",
        "metric_type": "Paired result structure",
        "short_purpose": "Compares algorithms using held-out recording or fold-level metric values.",
        "formula": "Fold table = rows as held-out folds, columns as algorithms, values as selected metric scores",
        "direction": "Depends on the selected metric",
        "interpretation": "A clear fold table makes the comparison fair because each algorithm is compared on the same held-out recordings.",
        "implementation": "pandas.pivot_table(results, index='Fold', columns='Algorithm', values='Value')",
    },
    {
        "name": "Descriptive statistics",
        "category": "Level 2: Statistical treatment",
        "metric_type": "Summary statistics",
        "short_purpose": "Summarizes each algorithm and metric using central tendency and variability.",
        "formula": "Mean = sum(x) / n; SD = sqrt(sum((x - mean)^2) / (n - 1)); IQR = Q3 - Q1",
        "direction": "Depends on the selected metric",
        "interpretation": "Descriptive statistics show the typical performance and spread of results across folds.",
        "implementation": "pandas.groupby(['Metric','Algorithm'])['Value'].agg(['mean','median','std','min','max'])",
    },
    {
        "name": "Algorithm ranking consistency",
        "category": "Level 2: Statistical treatment",
        "metric_type": "Rank summary",
        "short_purpose": "Checks whether the same algorithm ranks better consistently across folds and measures.",
        "formula": "Mean rank = sum(algorithm rank per fold) / number of folds",
        "direction": "Lower rank is better when rank 1 is best",
        "interpretation": "Consistent ranking helps identify whether a result appears stable across recordings, not only strong in one fold.",
        "implementation": "df.groupby(['Metric','Fold'])['Value'].rank(ascending=metric_lower_is_better)",
    },
    {
        "name": "Friedman test",
        "category": "Level 2: Statistical treatment",
        "metric_type": "Non-parametric omnibus test",
        "short_purpose": "Tests whether at least one of the three algorithms differs on a paired fold-level metric.",
        "formula": "Friedman chi-square is computed from algorithm ranks across paired folds",
        "direction": "p-value below alpha suggests a difference among algorithms",
        "interpretation": "A significant result suggests that at least one algorithm differs, but it does not identify which pair differs.",
        "implementation": "scipy.stats.friedmanchisquare(markov_values, gru_values, lstm_values)",
    },
    {
        "name": "Wilcoxon signed-rank test",
        "category": "Level 2: Statistical treatment",
        "metric_type": "Non-parametric pairwise test",
        "short_purpose": "Compares two algorithms using paired fold-level differences.",
        "formula": "W = min(sum of positive signed ranks, sum of negative signed ranks)",
        "direction": "p-value below corrected alpha suggests a pairwise difference",
        "interpretation": "A significant result suggests one pair differs on the selected metric under paired fold comparison.",
        "implementation": "scipy.stats.wilcoxon(algorithm_a_values, algorithm_b_values)",
    },
    {
        "name": "Multiple-comparison correction",
        "category": "Level 2: Statistical treatment",
        "metric_type": "Error-control procedure",
        "short_purpose": "Controls false-positive risk when several pairwise tests or metric comparisons are performed.",
        "formula": "Holm rule: compare ordered p_i with alpha / (m - i + 1)",
        "direction": "Smaller adjusted p-values provide stronger evidence",
        "interpretation": "Correction makes pairwise conclusions more cautious when several tests are reported.",
        "implementation": "statsmodels.stats.multitest.multipletests(p_values, method='holm')",
    },
    {
        "name": "Effect size and practical interpretation",
        "category": "Level 2: Statistical treatment",
        "metric_type": "Practical difference",
        "short_purpose": "Reports paired differences and practical importance beyond p-values.",
        "formula": "Paired difference = metric_A - metric_B; Wilcoxon effect size r = Z / sqrt(N)",
        "direction": "Depends on metric direction and comparison target",
        "interpretation": "Effect size helps explain whether an observed difference is meaningful, not merely statistically flagged.",
        "implementation": "custom paired differences, mean difference, median difference, and effect-size report",
    },
    {
        "name": "Overfitting analysis",
        "category": "Level 2: Statistical treatment",
        "metric_type": "Generalization interpretation",
        "short_purpose": "Interprets training, validation, and held-out gaps, learning curves, and seed variability.",
        "formula": "Overfitting gap = training score - held-out score, adjusted by metric direction",
        "direction": "Smaller harmful gap is preferred",
        "interpretation": "Large gaps may mean the model memorized the training data instead of generalizing to held-out recordings.",
        "implementation": "custom comparison of training logs, validation logs, held-out metrics, and seed-run summaries",
    },
]
